### ISSUE TITLE
Export for web?

### ISSUE THREAD

**Issue by keita-makino** [mathewleland/export-svg-with-styles#2]
I came here from `raect-vis` community, and wondering if there will be a feature that enables us to exporting the svg as `<img />` html tag for further use. Ideally, it could be combined with some pdf-realted libraries (e.g., `jspdf-react`).

Would this be feasible and beneficial?

**Comment by mathewleland** [comment]
I think this might be a niche case if you wanted the html tag with its styles, so while I don't think it would often be a use case for this package (or at least outside of the scope of what it's supposed to be now), I hope I can point you in the right direction:

if you fork this repository and then edit the exported function here on line 104 
https://github.com/mathewleland/export-svg-with-styles/blob/master/index.js#L104

Then you should just be able to prematurely return the variable, which should be the svg element as a tag supplied with all of its styles, ie `<svg background:'red' etc .. ></svg>`. 

So if you just type `return svgString` on line 104, this should give you what you want out of the exported function.

Depending on how you want to work with it going forward, it might require some parsing after, too, but let me know if this gets you in the right direction.

**Comment by keita-makino** [comment]
Oh my html tag was not shown as it's closed with `<` and `>`... Updated.  
Basically I want make it an image in html.
